"""
Grant application draft generation using Claude API.
Given a foundation and target org profile, generates a first-pass
grant letter narrative.
"""

import os
from typing import Optional

from src.api.propublica import ProPublicaClient, parse_filing
from src.commands.grants import list_foundation_grants
from src.export.report import fmt_dollar

try:
    import anthropic
    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False

MODEL = "claude-sonnet-4-20250514"
MAX_TOKENS = 2000


def generate_grant_draft(
    client: ProPublicaClient,
    foundation_ein: str,
    target_profile: dict,
    output_file: str = None,
) -> Optional[str]:
    """Generate a grant application draft letter.

    Args:
        client: ProPublica API client
        foundation_ein: Foundation EIN to apply to
        target_profile: Target org profile dict (name, mission, etc.)
        output_file: Optional file path to write draft to

    Returns:
        Draft text, or None if generation fails.
    """
    if not HAS_ANTHROPIC:
        print("  Error: anthropic package not installed. Run: pip install anthropic")
        return None

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("  Error: ANTHROPIC_API_KEY environment variable not set.")
        return None

    # Fetch foundation details
    ein_clean = foundation_ein.replace("-", "")
    print(f"  Fetching foundation details for EIN {ein_clean}...")

    detail = client.get_organization(ein_clean)
    if not detail:
        print(f"  Foundation not found: {foundation_ein}")
        return None

    org_info = detail.get("organization", {})
    foundation_name = org_info.get("name", "Unknown Foundation")
    filings = detail.get("filings_with_data", [])

    # Get filing financials
    filing_context = ""
    if filings:
        f = filings[0]
        assets = f.get("totassetsend") or 0
        grants = f.get("totgrntsamt") or 0
        filing_context = f"""
Foundation Financial Profile:
- Total Assets: {fmt_dollar(assets)}
- Total Grants Paid: {fmt_dollar(grants)}
- Tax Year: {f.get('tax_prd_yr', 'unknown')}"""

    # Fetch recent grants to understand giving patterns
    print(f"  Fetching recent grants from {foundation_name}...")
    grants = list_foundation_grants(
        client, ein_clean,
        funder_name=foundation_name,
        max_years=2,
    )

    grant_context = ""
    if grants:
        grant_lines = []
        for g in grants[:20]:
            amt = f"${g.amount:,.0f}" if g.amount else "unknown"
            grant_lines.append(f"- {g.recipient_name}: {amt} for {g.purpose or 'general support'}")
        grant_context = f"\nRecent Grants by {foundation_name}:\n" + "\n".join(grant_lines)

    # Build the prompt
    target_name = target_profile.get("name", "Our Organization")
    target_mission = target_profile.get("mission", "")
    target_city = target_profile.get("city", "")
    target_state = target_profile.get("state", "")
    target_ein = target_profile.get("ein", "")

    prompt = f"""Write a first draft of a grant application letter from a nonprofit to a foundation.

APPLYING ORGANIZATION:
Name: {target_name}
Location: {target_city}, {target_state}
EIN: {target_ein}
Mission: {target_mission}

TARGET FOUNDATION:
Name: {foundation_name}
EIN: {foundation_ein}
{filing_context}
{grant_context}

Write a compelling 1-2 page grant letter that:
1. Opens with a strong connection between our mission and the foundation's giving priorities
2. Clearly states who we are and what we do
3. Describes a specific program or need that aligns with their funding patterns
4. References their existing grants to similar organizations (if applicable)
5. Includes a specific funding request amount (suggest an appropriate amount based on their typical grant sizes)
6. Closes with next steps and contact information placeholders

Format as a professional letter. Use [BRACKETS] for any information that needs to be filled in.
Mark sections that need the most customization with "*** CUSTOMIZE:" notes."""

    print(f"  Generating draft with Claude...")

    try:
        ai_client = anthropic.Anthropic()
        response = ai_client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            messages=[{"role": "user", "content": prompt}],
        )

        draft = response.content[0].text.strip()

        if output_file:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(f"# Grant Application Draft\n")
                f.write(f"# To: {foundation_name} ({foundation_ein})\n")
                f.write(f"# From: {target_name}\n")
                f.write(f"# Generated by 990 Prospect Explorer\n\n")
                f.write(draft)
            print(f"\n  Draft saved to {output_file}")
        else:
            print(f"\n{'=' * 70}")
            print(f"  GRANT APPLICATION DRAFT")
            print(f"  To: {foundation_name}")
            print(f"  From: {target_name}")
            print(f"{'=' * 70}\n")
            print(draft)

        return draft

    except Exception as e:
        print(f"  [Error generating draft] {e}")
        return None


def cmd_draft(args, client: ProPublicaClient):
    """Generate a grant application draft (CLI command)."""
    import json

    if not args.ein:
        print("Please provide --ein for the target foundation.")
        return

    # Load target org profile
    profile_path = args.profile
    if not os.path.exists(profile_path):
        profile_path = os.path.join("profiles", f"{args.profile}.json")
    if not os.path.exists(profile_path):
        print(f"Profile not found: {args.profile}")
        print("Provide a path to a JSON profile or a name matching profiles/<name>.json")
        return

    with open(profile_path, "r") as f:
        profile = json.load(f)

    print(f"\n{'=' * 70}")
    print(f"  GRANT APPLICATION DRAFT GENERATOR")
    print(f"  Target Foundation EIN: {args.ein}")
    print(f"  Applying Org: {profile['name']}")
    print(f"{'=' * 70}")

    generate_grant_draft(
        client,
        foundation_ein=args.ein,
        target_profile=profile,
        output_file=args.output,
    )
